[general]
import = [
    "C:\\Users\\indie\\AppData\\Roaming\\alacritty\\themes\\themes\\dracula.toml"
#
# THEMES:
# https://github.com/alacritty/alacritty-theme
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[font]
size = 14

[font.normal]
family = "MonoLisa"
#family = "FiraCode Nerd Font Mono"
#family = "Hack Nerd Font"
#family = "JetBrains Mono"

[window]
decorations = "None"
dynamic_padding = true
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

[terminal.shell]
program = "wsl"
args = [
    "--cd",
    "~"
]

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"
